// Code generated by protoc-gen-go.
// source: header.proto
// DO NOT EDIT!

/*
Package packet_data is a generated protocol buffer package.

It is generated from these files:
	header.proto
	move.proto

It has these top-level messages:
	Header
*/
package packet_data

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type PacketType int32

const (
	PacketType_LoginType PacketType = 1
	PacketType_MoveType  PacketType = 2
)

var PacketType_name = map[int32]string{
	1: "LoginType",
	2: "MoveType",
}
var PacketType_value = map[string]int32{
	"LoginType": 1,
	"MoveType":  2,
}

func (x PacketType) Enum() *PacketType {
	p := new(PacketType)
	*p = x
	return p
}
func (x PacketType) String() string {
	return proto.EnumName(PacketType_name, int32(x))
}
func (x *PacketType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PacketType_value, data, "PacketType")
	if err != nil {
		return err
	}
	*x = PacketType(value)
	return nil
}

type Header struct {
	BodySize         *int32      `protobuf:"fixed32,1,req,name=body_size" json:"body_size,omitempty"`
	PacketType       *PacketType `protobuf:"varint,2,req,name=packet_type,enum=packet_data.PacketType" json:"packet_type,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}

func (m *Header) GetBodySize() int32 {
	if m != nil && m.BodySize != nil {
		return *m.BodySize
	}
	return 0
}

func (m *Header) GetPacketType() PacketType {
	if m != nil && m.PacketType != nil {
		return *m.PacketType
	}
	return PacketType_LoginType
}

func init() {
	proto.RegisterEnum("packet_data.PacketType", PacketType_name, PacketType_value)
}
